/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.veterinaria.GUI;

import DAO.DAOMascotaImpl;
import DAO.DAOTipoImpl;
import com.mycompany.veterinaria.clases.Mascota;
import com.mycompany.veterinaria.clases.TipoMascota;
import com.mycompany.veterinaria.conexion.conexion;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author aleji
 */
public class InsertUser extends javax.swing.JPanel {
    private String documentoDueño;
    private String NombreMascota;
    private int Tipo;
    private String raza;
    private String Dueño;
    private int Edad;
    private Date FechaNacimiento;
    private List<TipoMascota> lista;
    
    
    /**
     * Creates new form InsertUser
     */
    public InsertUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DocumentoDueño = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NombrePet = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ListaTipo = new javax.swing.JComboBox<TipoMascota>();
        jLabel4 = new javax.swing.JLabel();
        Raza = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        NombreAmo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        EdadPet = new javax.swing.JTextField();
        jScrollBar1 = new javax.swing.JScrollBar();
        jButton1 = new javax.swing.JButton();
        Fecha = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DocumentoDueño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocumentoDueñoActionPerformed(evt);
            }
        });
        add(DocumentoDueño, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 180, -1));

        jLabel1.setText("Documento del Dueño");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 180, -1));

        jLabel2.setText("Nombre de la mascota");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 180, -1));

        NombrePet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombrePetActionPerformed(evt);
            }
        });
        add(NombrePet, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 180, -1));

        jLabel3.setText("Tipo de Mascota");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 180, -1));

        DAOTipoImpl dao = new DAOTipoImpl();
        try {
            lista = dao.Listado();
        }catch(Exception ex){
        }
        DefaultComboBoxModel<TipoMascota> model = new DefaultComboBoxModel<>(lista.toArray(new TipoMascota[0]));
        ListaTipo.setModel(model);
        ListaTipo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ListaTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaTipoActionPerformed(evt);
            }
        });
        add(ListaTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 180, -1));

        jLabel4.setText("Raza de la Mascota");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 140, -1));

        Raza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RazaActionPerformed(evt);
            }
        });
        add(Raza, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 180, -1));

        jLabel5.setText("Nombre del Dueño");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 110, -1));

        NombreAmo.setForeground(new java.awt.Color(204, 204, 204));
        NombreAmo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreAmoActionPerformed(evt);
            }
        });
        add(NombreAmo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 180, 20));

        jLabel6.setText("Edad de la mascota");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, 20));

        EdadPet.setForeground(new java.awt.Color(204, 204, 204));
        EdadPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdadPetActionPerformed(evt);
            }
        });
        add(EdadPet, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 180, -1));
        add(jScrollBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(722, 0, -1, 431));

        jButton1.setText("Subir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 113, 48));

        Fecha.setDateFormatString("yyyy-MM-dd");
        add(Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 134, -1));

        jLabel7.setText("Inserte la Fecha");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 22, -1, -1));

        jButton2.setText("Añadir Tipo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 113, 48));
    }// </editor-fold>//GEN-END:initComponents

    private void DocumentoDueñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocumentoDueñoActionPerformed
        documentoDueño = DocumentoDueño.getText();
    }//GEN-LAST:event_DocumentoDueñoActionPerformed

    private void ListaTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaTipoActionPerformed
        Tipo = ListaTipo.getSelectedIndex();
    }//GEN-LAST:event_ListaTipoActionPerformed

    private void NombrePetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombrePetActionPerformed
        NombreMascota = NombrePet.getText();
    }//GEN-LAST:event_NombrePetActionPerformed

    private void NombreAmoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreAmoActionPerformed
        Dueño = NombreAmo.getText();
    }//GEN-LAST:event_NombreAmoActionPerformed

    private void EdadPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdadPetActionPerformed
        try {
            Edad = Integer.getInteger(EdadPet.getText());
        } catch(NumberFormatException ex){
            
        }
    }//GEN-LAST:event_EdadPetActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FechaNacimiento =  Fecha.getDate();
        Mascota user = new Mascota(documentoDueño, NombreMascota, Tipo, raza, Dueño, Edad, FechaNacimiento);
        DAOMascotaImpl up = new DAOMascotaImpl();
        try {
            up.Registrar(user);
        } catch (Exception ex) {
            Logger.getLogger(InsertUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void RazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RazaActionPerformed
        raza = Raza.getText();
    }//GEN-LAST:event_RazaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try { 
            String dsc = JOptionPane.showInputDialog("Inserte El Tipo de Mascota");
            TipoMascota tm = new TipoMascota(dsc);
            DAOTipoImpl user = new DAOTipoImpl();
            user.Registar(tm);
        } catch (Exception ex) {
            Logger.getLogger(InsertUser.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DocumentoDueño;
    private javax.swing.JTextField EdadPet;
    private com.toedter.calendar.JDateChooser Fecha;
    private javax.swing.JComboBox<TipoMascota> ListaTipo;
    private javax.swing.JTextField NombreAmo;
    private javax.swing.JTextField NombrePet;
    private javax.swing.JTextField Raza;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollBar jScrollBar1;
    // End of variables declaration//GEN-END:variables
}
